services:
  configSrv:
    image: mongo:latest
    container_name: configSrv
    ports:
      - "27017:27017"
    command:
      [
        "--configsvr",
        "--replSet", "config_server",
        "--bind_ip_all",
        "--port", "27017"
      ]
    volumes:
      - config-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mongo-network

  shard1-1:
    image: mongo:latest
    container_name: shard1-1
    ports:
      - "27021:27021"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard1",
        "--bind_ip_all",
        "--port", "27021"
      ]
    volumes:
      - shard1-1-data:/data/db
    links:
      - shard1-2
      - shard1-3
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27021", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network
  
  shard1-2:
    image: mongo:latest
    container_name: shard1-2
    ports:
      - "27022:27022"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard1",
        "--bind_ip_all",
        "--port", "27022"
      ]
    volumes:
      - shard1-2-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27022", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network
  
  shard1-3:
    image: mongo:latest
    container_name: shard1-3
    ports:
      - "27023:27023"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard1",
        "--bind_ip_all",
        "--port", "27023"
      ]
    volumes:
      - shard1-3-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27023", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network

  shard2-1:
    image: mongo:latest
    container_name: shard2-1
    ports:
      - "27024:27024"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard2",
        "--bind_ip_all",
        "--port", "27024"
      ]
    volumes:
      - shard2-1-data:/data/db
    links:
      - shard2-2
      - shard2-3
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27024", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network
  
  shard2-2:
    image: mongo:latest
    container_name: shard2-2
    ports:
      - "27025:27025"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard2",
        "--bind_ip_all",
        "--port", "27025"
      ]
    volumes:
      - shard2-2-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27025", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network

  shard2-3:
    image: mongo:latest
    container_name: shard2-3
    ports:
      - "27026:27026"
    command:
      [
        "--shardsvr",
        "--replSet", "rs-shard2",
        "--bind_ip_all",
        "--port", "27026"
      ]
    volumes:
      - shard2-3-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27026", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      configSrv:
        condition: service_healthy
    networks:
      - mongo-network

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    ports:
      - "27020:27020"
    command:
      [
        "mongos",
        "--configdb", "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port", "27020"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      shard1-1:
        condition: service_healthy
      shard1-2:
        condition: service_healthy
      shard1-3:
        condition: service_healthy
      shard2-1:
        condition: service_healthy
      shard2-2:
        condition: service_healthy
      shard2-3:
        condition: service_healthy
    networks:
      - mongo-network

  api_app:
    build:
      context: ./api_app
    container_name: api_app
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: mongodb://mongos_router:27020
      MONGODB_DATABASE_NAME: somedb
    networks:
      - mongo-network

volumes:
  config-data:
  shard1-1-data:
  shard1-2-data:
  shard1-3-data:
  shard2-1-data:
  shard2-2-data:
  shard2-3-data:

networks:
  mongo-network:
    driver: bridge